[package]
name = "wipple-frontend"
version = "0.0.0"
edition = "2021"

[features]
default = []
serde = ["dep:serde", "lasso/serialize", "backtrace/serialize-serde", "im/serde"]

[dependencies]
anyhow = "1"
arbitrary = { version = "1", features = ["derive"], optional = true }
async-recursion = "1"
async-trait = "0.1"
backtrace = "0.3"
codespan-reporting = "0.11"
clap = { version = "3", features = ["derive"], optional = true }
enum_dispatch = "0.3"
futures = "0.3"
im = "15"
indexmap = "1"
itertools = "0.10"
lasso = { version = "0.6", features = ["multi-threaded"] }
lazy_static = "1"
logos = "0.12"
parking_lot = "0.12"
paste = "1"
peg = "0.8"
petgraph = "0.6"
regex = "1"
replace_with = "0.1"
rust_decimal = "1"
rustc_lexer = "0.1"
serde = { version = "1", features = ["derive", "rc"], optional = true }
strum = { version = "0.24", features = ["derive"] }
