[package]
name = "wipple-frontend"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-recursion = "1"
async-trait = "0.1"
backtrace = { version = "0.3", features = ["serde"] }
codespan-reporting = "0.11"
clap = { version = "3", features = ["derive"], optional = true }
futures = "0.3"
im = { version = "15", features = ["serde"] }
indexmap = "1"
itertools = "0.10"
lasso = { version = "0.6", features = ["multi-threaded", "serialize"] }
lazy_static = "1"
logos = "0.12"
parking_lot = { version = "0.12", features = ["serde"] }
paste = "1"
peg = "0.8"
petgraph = "0.6"
regex = "1"
rust_decimal = "1"
rustc_lexer = "0.1"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = { version = "1", optional = true }
strum = { version = "0.24", features = ["derive"] }
