[build]
publish = "site/dist"

[dev]
framework = "#static"

[build.processing.html]
pretty_urls = true

[[headers]]
for = "/playground/*"
[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"
