version: "3"

tasks:
  compiler:
    cmds:
      - go run ./compiler {{.CLI_ARGS}}
  test:
    cmds:
      - go test work {{.CLI_ARGS}}
  install:
    cmds:
      - go install ./compiler
  vscode:
    dir: vscode
    cmds:
      - npm run extension

  setup:
    deps:
      - setup:playground
      - setup:site
  setup:playground:
    dir: playground
    cmds:
      - npm install
  setup:site:
    dir: site
    cmds:
      - npm install

  serve:
    deps:
      - serve:library
      - serve:playground
      - serve:server
  serve:library:
    dir: library
    cmds:
      - npx serve & task serve:library:watch
    env:
      PORT: "3001"
  serve:library:watch:
    dir: library
    watch: true
    sources:
      - src/**/*
    cmds:
      - node build.js
  serve:playground:
    dir: playground
    cmds:
      - npm run dev -- --open
  serve:server:
    dir: .
    cmds:
      - go run ./compiler -- server
    env:
      PORT: "3000"
      LIBRARY_URL: "http://localhost:3001"
      MONGO_URI: "mongodb://localhost:27017"
      MONGO_DB_NAME: "wipple-share"

  build:
    deps:
      - build:library
      - build:playground
      - build:functions
    dir: site
    cmds:
      - rm -rf dist
      - npm run build
      - cp -r ../library/dist/. dist/library
      - cp -r ../playground/build/. dist/playground
  build:library:
    dir: library
    cmds:
      - node build.js
  build:playground:
    dir: playground
    cmds:
      - npm run build
  build:functions:
    dir: .
    cmds:
      - rm -rf netlify/functions && mkdir -p netlify/functions
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o netlify/functions/api ./compiler
