version: "3"

tasks:
  setup:
    deps:
      - setup:playground
      - setup:site
  setup:playground:
    dir: playground
    cmds:
      - npm install
  setup:site:
    dir: site
    cmds:
      - npm install

  dev:site:
    deps:
      - dev:playground
      - dev:server
  dev:playground:
    dir: playground
    cmds:
      - npm run dev -- --open
  dev:server:
    dir: .
    cmds:
      - RUST_LOG=debug PORT=3000 cargo run --bin=wipple-api {{.CLI_ARGS}}

  dev:cli:
    dir: .
    cmds:
      - cargo run --bin=wipple {{.CLI_ARGS}}

  test:
    dir: .
    ignore_error: true
    cmd: |
      bash -c '
      cargo build --package=wipple-api
      PORT=3001 ./target/debug/wipple-api & test_server_pid=$!
      sleep 1
      TESTS_SERVER_URL='http://localhost:3001' node --experimental-vm-modules {{.CLI_ARGS}} test/index.js
      kill $test_server_pid
      '
  test:update-snapshots:
    cmds:
      - task: test
        vars:
          CLI_ARGS: --test-update-snapshots

  build:site:
    deps:
      - build:docs
      - build:playground
    dir: site
    cmds:
      - rm -rf dist
      - npm run build
      - cp -r ../playground/build/. dist/playground
      - cp -r ../docs/book/. dist/docs
  build:docs:
    dir: docs
    cmds:
      - cargo binstall mdbook
      - mdbook build
  build:playground:
    dir: playground
    cmds:
      - npm run build

  install:
    deps:
      - install:cli
  install:cli:
    dir: cli
    cmds:
      - cargo install --path=. --force
