version: "3"

tasks:
    run:
        run: once
        cmds:
            - cargo run --bin wipple -- run {{.CLI_ARGS}}

    compile:
        run: once
        cmds:
            - cargo run --bin wipple -- compile {{.CLI_ARGS}}

    test:
        run: once
        cmds:
            - cargo run --bin wipple-test -- tests {{.CLI_ARGS}}

    cli:
        run: once
        cmds:
            - cargo install --force --path tools/cli

    serve:
        run: once
        cmds:
            - task: website
            - npx http-server -c-1 website/_site --cors

    website:
        run: once
        deps:
            - cli
            - website-home
            - website-compiler-docs
            - website-shared
            - website-embed
            - website-playground
            - website-std
            - website-doc

    website-home:
        run: once
        deps:
            - cli
        dir: website/home
        cmds:
            - npm i
            - npm run build
            - mkdir -p ../_site
            - cp -r ./_site/* ../_site
        sources:
            - images/**/*
            - prism/**/*
            - styles/**/*
            - .eleventy.js
            - index.html
            - package.json
            - postcss.config.cjs
            - tailwind.config.cjs
            - robots.txt
        generates:
            - ../_site/images/**/*
            - ../_site/styles/**/*
            - ../_site/index.html
            - ../_site/robots.txt

    website-compiler-docs:
        run: once
        deps:
            - website-home
        dir: website/compiler-docs
        cmds:
            - mdbook build
            - mkdir -p ../_site/compiler-docs
            - cp -r book/* ../_site/compiler-docs
        sources:
            - scripts/**/*
            - src/**/*
            - theme/**/*
            - book.toml
        generates:
            - ../_site/book/**/*

    website-shared:
        run: once
        deps:
            - website-home
        dir: website/shared
        cmds:
            - (cd .. && npm i)
            - npm run build
        sources:
            - src/**/*
            - wasm/**/*
            - build.js
            - tsconfig.json
            - tsconfig.node.json
        generates:
            - dist/**/*

    website-playground:
        run: once
        deps:
            - website-shared
        dir: website/playground
        cmds:
            - task build
            - mkdir -p ../_site/playground
            - cp -r dist/* ../_site/playground
        # 'sources' and 'generates' are located in website/playground/Taskfile.yml

    website-embed:
        run: once
        deps:
            - website-shared
            - website-playground
        dir: website/embed
        cmds:
            - npm run build
            - mkdir -p ../_site/embed
            - cp -r dist/* ../_site/embed
        sources:
            - src/**/*
            - index.html
            - package.json
            - postcss.config.cjs
            - tailwind.config.cjs
            - tsconfig.json
            - tsconfig.node.json
            - vite.config.ts
        generates:
            - ../_site/embed/**/*

    website-std:
        run: once
        deps:
            - website-home
        dir: website
        cmds:
            - mkdir -p _site/std
            - cp -r ../std/* _site/std
        sources:
            - ../_std/**/*
        generates:
            - _site/std/**/*

    website-doc:
        run: once
        deps:
            - website-playground
        dir: website
        cmds:
            - mkdir -p _site/doc
            - >
                wipple doc ../std/std.wpl
                --title 'Wipple Standard Library'
                --image 'https://wipple.dev/images/logo.svg'
                --link 'https://wipple.dev'
                --include-builtins
                --std ../std/std.wpl
                > _site/doc/std.html
            - mv _site/playground/doc/*.html _site/doc
        sources:
            - ../std/**/*
            - _site/playground/doc/*.html
        generates:
            - _site/doc/**/*
