version: "3"

tasks:
    dev:
        run: once
        cmds:
            - task: compile
            - .wipple/out

    test:
        run: once
        cmds:
            - cargo test --package=wipple-test -- {{.CLI_ARGS}}

    test-with-coverage:
        run: once
        cmds:
            - RUSTFLAGS="-Cinstrument-coverage -Clink-dead-code" LLVM_PROFILE_FILE="./target/debug/coverage-%p-%m.profraw" cargo test --package=wipple-test -- --test-threads=1 {{.CLI_ARGS}}
            - task: coverage

    coverage:
        run: once
        cmds:
            - |
                if ! [[ -z "$CI" ]]; then
                    rustup component add llvm-tools-preview
                fi

                if ! command -v grcov; then
                    cargo install grcov --force
                fi
            - rm -rf coverage && mkdir -p coverage
            - grcov . --binary-path target/debug/ -s . -t cobertura,html --branch --ignore-not-existing --keep-only 'compiler/**/*' --keep-only 'interpreter/**/*' --keep-only 'render/**/*' -o coverage

    # doctest:
    #     run: once
    #     cmds:
    #         - rm -rf .wipple/doctest && mkdir -p .wipple/doctest
    #         - for f in web/docs/src/tour/*.md; do echo -e "testing $(basename $f)" && wipple doctest $f --dependency .wipple/base.wippleinterface --link .wipple/base.wipplelibrary > .wipple/doctest/$(basename $f).xml; done

    compile:
        run: once
        deps:
            - base:compile
        cmds:
            - cargo run --bin wipple -- compile test.wipple --dependency .wipple/base.wippleinterface --interface .wipple/test.wippleinterface --library .wipple/test.wipplelibrary
            - cargo run --bin wipple -- link .wipple/*.wipplelibrary --output .wipple/out

    cli:install:
        run: once
        dir: cli
        cmds:
            - cargo install --bin wipple --path . --force

    vscode:install:
        run: once
        dir: vscode
        cmds:
            - npx @vscode/vsce package --no-dependencies --skip-license --allow-missing-repository
            - code --install-extension wipple-vscode-0.0.0.vsix
            - rm wipple-vscode-0.0.0.vsix

    web:install-dependencies:
        run: once
        deps:
            - if ! command -v wasm-pack; then cargo install --force wasm-pack; fi
            - web:home:install-dependencies
            - web:login:install-dependencies
            - web:docs:install-dependencies
            - web:playground:install-dependencies

    web:serve:
        run: once
        deps:
            - web:build
        cmds:
            - netlify dev

    web:build:
        run: once
        deps:
            - web:home:build
            - web:login:build
            - web:docs:build
            - web:playground:build
        dir: web
        cmds:
            - rm -rf dist && mkdir dist
            - cp -r home/_site/. dist
            - cp -r login/dist/. dist/login
            - cp -r docs/book/. dist/docs
            - cp -r playground/dist/. dist/playground

    web:home:install-dependencies:
        run: once
        dir: web/home
        cmds:
            - npm install

    web:home:serve:
        run: once
        dir: web/home
        cmds:
            - npm run dev

    web:home:build:
        run: once
        dir: web/home
        cmds:
            - npm run build

    web:login:install-dependencies:
        run: once
        dir: web/login
        cmds:
            - npm install

    web:login:serve:
        run: once
        dir: web/login
        cmds:
            - npm run dev

    web:login:build:
        run: once
        dir: web/login
        cmds:
            - npm run build

    web:docs:install-dependencies:
        run: once
        dir: web/docs
        cmds:
            - if ! command -v mdbook; then cargo install --force mdbook; fi
            - if ! command -v mdbook-template; then cargo install --force mdbook-template; fi

    web:docs:prepare:
        run: once
        dir: web/docs
        cmds:
            - (cd ../../compiler && cargo test render_grammar_to_html)

    web:docs:serve:
        run: once
        deps:
            - web:docs:prepare
        dir: web/docs
        cmds:
            - mdbook serve

    web:docs:build:
        run: once
        deps:
            - web:docs:prepare
        dir: web/docs
        cmds:
            - mdbook build

    web:playground:install-dependencies:
        run: once
        dir: web/playground
        cmds:
            - npm install

    web:playground:bundle:
        run: once
        dir: web/playground
        cmds:
            - task base:compile
            - cargo run --bin wipple -- compile ../../library/base/*.wipple --interface ../../.wipple/base.wippleinterface --library ../../.wipple/base.wipplelibrary
            - cargo run --bin wipple -- bundle-for-playground ../../library/base/*.wipple --output ./public/library/base.wipplebundle
            - cargo run --bin wipple -- bundle-for-playground ../../library/playground/turtle.wipple --dependency ../../.wipple/base.wippleinterface --link ../../.wipple/base.wipplelibrary --output ./public/library/turtle.wipplebundle
            - cargo run --bin wipple -- bundle-for-playground ../../library/playground/music.wipple --dependency ../../.wipple/base.wippleinterface --link ../../.wipple/base.wipplelibrary --output ./public/library/music.wipplebundle
            - cargo run --bin wipple -- bundle-for-playground ../../library/playground/math.wipple --dependency ../../.wipple/base.wippleinterface --link ../../.wipple/base.wipplelibrary --output ./public/library/math.wipplebundle
            - cargo run --bin wipple -- bundle-for-playground ../../library/playground/game.wipple --dependency ../../.wipple/base.wippleinterface --link ../../.wipple/base.wipplelibrary --output ./public/library/game.wipplebundle
            - cargo run --bin wipple -- bundle-for-playground ../../library/playground/physics.wipple --dependency ../../.wipple/base.wippleinterface --link ../../.wipple/base.wipplelibrary --output ./public/library/physics.wipplebundle
            - cp -r ../../library/help ./public/library

    web:playground:serve:
        run: once
        deps:
            - web:playground:bundle
        dir: web/playground
        cmds:
            - ./wasm/build.sh
            - npm run dev

    web:playground:build:
        run: once
        deps:
            - web:playground:bundle
        dir: web/playground
        cmds:
            - ./wasm/build.sh
            - npm run build

    base:compile:
        run: once
        cmds:
            - rm -rf .wipple
            - cargo run --bin wipple -- compile library/base/*.wipple --interface .wipple/base.wippleinterface --library .wipple/base.wipplelibrary
