version: "3"

tasks:
  compiler:
    cmds:
      - cargo run --bin=wipple {{.CLI_ARGS}}
  test:
    cmds:
      - cargo build --bin=wipple
      - cargo insta test
      - node {{.CLI_ARGS}} test
  test:update:
    cmds:
      - INSTA_UPDATE=1 task test -- --test-update-snapshots
  test:coverage:
    cmd: bash -e coverage.sh
  install:
    cmds:
      - cargo install --path=compiler --bin=wipple
  vscode:
    dir: vscode
    cmds:
      - npm run extension

  setup:
    deps:
      - setup:playground
      - setup:site
  setup:playground:
    dir: playground
    cmds:
      - npm install
  setup:site:
    dir: site
    cmds:
      - npm install

  serve:site:
    dir: site
    cmds:
      - npm run dev -- --open
  serve:playground:
    deps:
      - serve:library
      - serve:server
      - serve:playground:watch
  serve:playground:watch:
    dir: playground
    cmds:
      - npm run dev -- --open
  serve:library:
    dir: library
    cmds:
      - npx serve & task serve:library:watch
    env:
      PORT: "3001"
  serve:library:watch:
    dir: library
    watch: true
    sources:
      - src/**/*
    cmds:
      - node build.js
  serve:server:
    cmds:
      - if [[ ! -v NO_SERVER ]]; then cargo lambda watch --bin=wipple-server --features=lambda; fi
    env:
      LIBRARY_URL: "http://localhost:3001"

  build:
    deps:
      - build:library
      - build:playground
      - build:functions
    dir: site
    cmds:
      - rm -rf dist
      - npm run build
      - cp -r ../library/dist/. dist/library
      - cp -r ../playground/build/. dist/playground
  build:library:
    dir: library
    cmds:
      - node build.js
  build:playground:
    dir: playground
    cmds:
      - npm run build
  build:functions:
    dir: .
    cmds:
      - rm -rf netlify/functions && mkdir -p netlify/functions
      - cargo lambda build --bin=wipple-server --target=x86_64-unknown-linux-musl --features=lambda --release
      - cp target/lambda/wipple-server/bootstrap netlify/functions/api
