version: "3"

tasks:
  dev:
    run: once
    deps:
      - cli:build
    cmds:
      - task: compile
      - $WIPPLE_TEST_PREFIX/.wipple/out

  test:
    run: once
    deps:
      - compiler:build
      - interpreter:build
      - base:compile
    dir: test
    cmds:
      - npm test -- {{.CLI_ARGS}}

  compile:
    run: once
    deps:
      - base:compile
    preconditions:
      - sh: |
          if [ -z "$WIPPLE_TEST_PREFIX" ]; then
            exit 1
          fi
        msg: WIPPLE_TEST_PREFIX is not set
    cmds:
      - wipple compile $WIPPLE_TEST_PREFIX/test.wipple --dependency $WIPPLE_TEST_PREFIX/.wipple/base.wippleinterface --interface $WIPPLE_TEST_PREFIX/.wipple/test.wippleinterface --library $WIPPLE_TEST_PREFIX/.wipple/test.wipplelibrary
      - wipple link $WIPPLE_TEST_PREFIX/.wipple/*.wipplelibrary --output $WIPPLE_TEST_PREFIX/.wipple/out

  inspect:
    run: once
    preconditions:
      - sh: |
          if [ -z "$WIPPLE_TEST_PREFIX" ]; then
            exit 1
          fi
        msg: WIPPLE_TEST_PREFIX is not set
    cmds:
      - code $WIPPLE_TEST_PREFIX/.wipple

  base:compile:
    run: once
    preconditions:
      - sh: |
          if [ -z "$WIPPLE_TEST_PREFIX" ]; then
            exit 1
          fi
        msg: WIPPLE_TEST_PREFIX is not set
    cmds:
      - rm -rf $WIPPLE_TEST_PREFIX/.wipple
      - wipple compile library/base/*.wipple --interface $WIPPLE_TEST_PREFIX/.wipple/base.wippleinterface --library $WIPPLE_TEST_PREFIX/.wipple/base.wipplelibrary

  cli:build:
    run: once
    deps:
      - compiler:build
      - interpreter:build
    dir: cli
    cmds:
      - npm run build
      - npm run package
      - cp dist/wipple /usr/local/bin/wipple

  compiler:build:
    run: once
    dir: compiler
    cmds:
      - npm run build

  interpreter:build:
    run: once
    dir: interpreter
    cmds:
      - npm run build
