version: "3"

run: once

tasks:
  compiler:
    cmds:
      - cargo run -- {{.CLI_ARGS}}
  test:
    cmds:
      - node {{.CLI_ARGS}} test
  test:update:
    cmds:
      - task test -- --test-update-snapshots
  install:
    cmds:
      - cargo install --path=compiler/cli

  setup:
    deps:
      - setup:api
      - setup:playground
      - setup:site
      - setup:server
  setup:api:
    dir: compiler/api
    cmds:
      - npm install
  setup:playground:
    dir: playground
    cmds:
      - npm install
  setup:site:
    dir: site
    cmds:
      - npm install
  setup:server:
    dir: server
    cmds:
      - npm install

  serve:site:
    dir: site
    cmds:
      - npm run dev -- --open
  serve:playground:
    deps:
      - serve:server
      - serve:playground:watch
  serve:playground:watch:
    dir: playground
    cmds:
      - npm run dev -- --open
  serve:server:
    dir: server
    deps:
      - build:server
    cmds:
      - PORT=9000 npm run dev

  build:
    deps:
      - build:library
      - build:playground
      - build:server
    dir: site
    cmds:
      - rm -rf dist
      - npm run build
      - cp -r ../library/dist/. dist/library
      - cp -r ../playground/build/. dist/playground
  build:library:
    dir: library
    cmds:
      - node build.js
  build:playground:
    dir: playground
    cmds:
      - npm run build
  build:api:
    dir: compiler/api
    cmds:
      - npm run build
  build:server:
    dir: server
    deps:
      - build:api
      - build:library
    cmds:
      - npm run build
      - rm -rf ../netlify/functions/api && mkdir -p ../netlify/functions/api &&
        cp dist/* ../netlify/functions/api/

  vscode:
    dir: vscode
    deps:
      - build:api
      - build:library
    cmds:
      - npm run extension
