version: "3"

tasks:
  setup:
    deps:
      - setup:playground
      - setup:site
  setup:playground:
    dir: playground
    cmds:
      - npm install
  setup:site:
    dir: site
    cmds:
      - npm install

  dev:site:
    deps:
      - dev:library
      - dev:playground
      - dev:server
  dev:library:
    dir: library
    cmds:
      - npx serve & task dev:library:watch
    env:
      PORT: "3001"
  dev:library:watch:
    dir: library
    watch: true
    sources:
      - src/**/*
    cmds:
      - node build.js
  dev:playground:
    dir: playground
    cmds:
      - npm run dev -- --open
  dev:server:
    dir: .
    cmds:
      - cargo run --bin=wipple-api {{.CLI_ARGS}}
    env:
      RUST_LOG: "trace"
      PORT: "3000"
      LIBRARY_URL: "http://localhost:3001"
      MONGO_URI: "mongodb://localhost:27017"
      MONGO_DB_NAME: "wipple-share"

  dev:cli:
    dir: .
    cmds:
      - cargo run --bin=wipple {{.CLI_ARGS}}

  test:
    dir: .
    ignore_error: true
    cmd: |
      bash -c '
      cargo build --package=wipple-api
      PORT=3001 ./target/debug/wipple-api & test_server_pid=$!
      sleep 1
      TESTS_SERVER_URL='http://localhost:3001' node --experimental-vm-modules {{.CLI_ARGS}} test/index.js
      kill $test_server_pid
      '
  test:update-snapshots:
    cmds:
      - task: test
        vars:
          CLI_ARGS: --test-update-snapshots

  build:site:
    deps:
      - build:docs
      - build:library
      - build:playground
    dir: site
    cmds:
      - rm -rf dist
      - npm run build
      - cp -r ../docs/book/. dist/docs
      - cp -r ../library/dist/. dist/library
      - cp -r ../playground/build/. dist/playground
  build:docs:
    dir: docs
    cmds:
      - cargo binstall mdbook
      - mdbook build
  build:library:
    dir: library
    cmds:
      - node build.js
  build:playground:
    dir: playground
    cmds:
      - npm run build

  install:
    deps:
      - install:cli
  install:cli:
    dir: cli
    cmds:
      - cargo install --path=. --force
