version: "3"

run: once

tasks:
  compiler:
    cmds:
      - cargo run -- {{.CLI_ARGS}}
  compiler:instruments:
    cmds:
      - cargo instruments --release -t cpu -- {{.CLI_ARGS}}
  test:
    cmds:
      - node {{.CLI_ARGS}} test
  test:update:
    cmds:
      - task test -- --test-update-snapshots
  install:
    cmds:
      - cargo install --path=compiler/cli

  setup:
    deps:
      - setup:api
      - setup:playground
      - setup:site
      - setup:docs
  setup:api:
    dir: compiler/api
    cmds:
      - npm install
  setup:playground:
    dir: playground
    cmds:
      - npm install
  setup:site:
    dir: site
    cmds:
      - npm install
  setup:docs:
    dir: docs
    cmds:
      - (cd theme/js && npm install)

  serve:site:
    dir: site
    cmds:
      - npm run dev -- --open
  serve:playground:
    deps:
      - build:api
      - build:library
    dir: playground
    cmds:
      - npm run dev -- --open
  serve:docs:
    dir: docs
    cmds:
      - (cd theme/js && npm run build)
      - mdbook serve

  build:
    deps:
      - build:library
      - build:playground
      - build:docs
    dir: site
    cmds:
      - rm -rf dist
      - npm run build
      - cp -r ../library/dist/. dist/library
      - cp -r ../playground/build/. dist/playground
      - cp -r ../docs/book/. dist/docs
  build:library:
    dir: library
    cmds:
      - node build.js
  build:playground:
    deps:
      - build:api
      - build:library
    dir: playground
    cmds:
      - npm run build
  build:api:
    dir: compiler/api
    cmds:
      - npm run build
  build:docs:
    dir: docs
    cmds:
      - (cd theme/js && npm run build)
      - mdbook build
  build:lsp:
    dir: ide/lsp
    deps:
      - build:api
      - build:library
    cmds:
      - npm run build

  vscode:
    dir: ide/vscode
    deps:
      - build:lsp
    cmds:
      - npm run extension
