version: "3"

tasks:
  dev:
    run: once
    deps:
      - cli:build
    cmds:
      - task: compile
      - $WIPPLE_TEST_PREFIX/.wipple/out

  test:
    run: once
    deps:
      - compiler:build
      - interpreter:build
      - base:compile
    dir: test
    cmds:
      - npm test -- {{.CLI_ARGS}}

  compile:
    run: once
    deps:
      - base:compile
    preconditions:
      - sh: |
          if [ -z "$WIPPLE_TEST_PREFIX" ]; then
            exit 1
          fi
        msg: WIPPLE_TEST_PREFIX is not set
    cmds:
      - wipple compile $WIPPLE_TEST_PREFIX/test.wipple --dependency $WIPPLE_TEST_PREFIX/.wipple/base.wippleinterface --interface $WIPPLE_TEST_PREFIX/.wipple/test.wippleinterface --library $WIPPLE_TEST_PREFIX/.wipple/test.wipplelibrary
      - wipple link $WIPPLE_TEST_PREFIX/.wipple/*.wipplelibrary --output $WIPPLE_TEST_PREFIX/.wipple/out

  inspect:
    run: once
    preconditions:
      - sh: |
          if [ -z "$WIPPLE_TEST_PREFIX" ]; then
            exit 1
          fi
        msg: WIPPLE_TEST_PREFIX is not set
    cmds:
      - code $WIPPLE_TEST_PREFIX/.wipple

  app:serve:
    run: once
    deps:
      - app:bundle-for-playground
    dir: app
    cmds:
      - npm run dev

  app:build:
    run: once
    deps:
      - app:bundle-for-playground
    dir: app
    cmds:
      - npm run build

  app:bundle-for-playground:
    run: once
    dir: app
    deps:
      - cli:build
      - base:compile
    cmds:
      - rm -rf $WIPPLE_TEST_PREFIX/.wipple
      - wipple compile ../library/base/*.wipple --interface $WIPPLE_TEST_PREFIX/.wipple/base.wippleinterface --library $WIPPLE_TEST_PREFIX/.wipple/base.wipplelibrary
      - wipple bundle-for-playground ../library/base/*.wipple --output ./public/library/base.wipplebundle
      - wipple bundle-for-playground ../library/playground/turtle.wipple --dependency $WIPPLE_TEST_PREFIX/.wipple/base.wippleinterface --link $WIPPLE_TEST_PREFIX/.wipple/base.wipplelibrary --output ./public/library/turtle.wipplebundle
      - cp -r ../library/help ./public/library

  base:compile:
    run: once
    preconditions:
      - sh: |
          if [ -z "$WIPPLE_TEST_PREFIX" ]; then
            exit 1
          fi
        msg: WIPPLE_TEST_PREFIX is not set
    cmds:
      - rm -rf $WIPPLE_TEST_PREFIX/.wipple
      - wipple compile library/base/*.wipple --interface $WIPPLE_TEST_PREFIX/.wipple/base.wippleinterface --library $WIPPLE_TEST_PREFIX/.wipple/base.wipplelibrary

  install-dependencies:
    run: once
    deps:
      - test:install-dependencies
      - cli:install-dependencies
      - compiler:install-dependencies
      - interpreter:install-dependencies

  test:install-dependencies:
    run: once
    dir: test
    cmds:
      - npm install

  cli:install-dependencies:
    run: once
    dir: cli
    cmds:
      - npm install

  cli:build:
    run: once
    deps:
      - compiler:build
      - interpreter:build
    dir: cli
    cmds:
      - npm run build
      - npm run package
      - cp dist/wipple /usr/local/bin/wipple

  compiler:install-dependencies:
    run: once
    dir: compiler
    cmds:
      - npm install

  compiler:build:
    run: once
    dir: compiler
    cmds:
      - npm run build

  interpreter:install-dependencies:
    run: once
    dir: interpreter
    cmds:
      - npm install

  interpreter:build:
    run: once
    deps:
      - compiler:build
    dir: interpreter
    cmds:
      - npm run build
