version: "3"

tasks:
  install:
    deps:
      - install:interpreter
      - install:playground
      - install:site
  install:interpreter:
    dir: interpreter
    cmds:
      - npm install
  install:playground:
    dir: playground
    cmds:
      - npm install
  install:site:
    dir: site
    cmds:
      - npm install

  dev:
    deps:
      - dev:playground
      - dev:server
  dev:playground:
    dir: playground
    cmds:
      - npm run dev -- --open
  dev:server:
    dir: server
    cmds:
      - RUST_LOG=debug PORT=3000 cargo run {{.CLI_ARGS}}

  build:web:
    deps:
      - build:ir-bindings
      - build:site
  build:ir-bindings:
    dir: compiler
    cmds:
      - cargo binstall typeshare-cli
      - typeshare . --lang=typescript --output-file=../interpreter/ir.d.ts
  build:site:
    deps:
      - build:playground
      - build:docs
    dir: site
    cmds:
      - rm -rf dist
      - npm run build
      - cp -r ../playground/build/. dist/playground
      - cp -r ../docs/book/. dist/docs
  build:docs:
    dir: docs
    cmds:
      - cargo binstall mdbook
      - mdbook build
  build:playground:
    dir: playground
    cmds:
      - npm run build
