version: "3"

tasks:
    build:
        deps:
            - playground
            - task: ui
              vars: { NAME: game }
            - task: ui
              vars: { NAME: graphing }
            - task: ui
              vars: { NAME: music }
            - task: ui
              vars: { NAME: turtle }

    playground:
        run: once
        cmds:
            - npm i
            - npm run build
        sources:
          - public/**/*
          - src/**/*
          - .env
          - index.html
          - package.json
          - package-lock.json
          - postcss.config.cjs
          - tailwind.config.cjs
          - tsconfig.json
          - tsconfig.node.json
          - vite.config.ts
        generates:
          - dist/assets/**/*
          - dist/files/**/*
          - dist/images/**/*
          - dist/lessons/**/*
          - dist/*.html

    ui:
        label: 'ui-{{.NAME}}'
        deps:
            - playground
        dir: ui/{{.NAME}}
        cmds:
            - mkdir -p ../../dist/doc
            - mkdir -p ../../dist/ui/{{.NAME}}
            - npm i
            - npm run build
            - cp dist/* ../../dist/ui/{{.NAME}}
        sources:
          - src/**/*
          - package.json
          - package-lock.json
          - tsconfig.json
          - tsconfig.node.json
          - vite.config.ts
        generates:
          - ../../dist/ui/{{.NAME}}/**/*
