[package]
name = "wipple_diagnostics"
version = "0.0.0"
edition = "2021"

[dependencies]
codemap = "=0.1.2"
codemap-diagnostic = "0.1"
internment = { version = "0.5", features = ["serde"] }
serde = { version = "1", features = ["derive", "rc"] }
