[package]
name = "wipple_projects"
version = "0.0.0"
edition = "2018"

[dependencies]
git2 = "0.13"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "native-tls", "native-tls-vendored"] }
rust-embed = "5"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
wipple = { path = "../../language" }
wipple_stdlib = { path = "../../library" }
wipple_parser = { path = "../../parser" }
wipple_plugins = { path = "../../tooling/plugins" }
zip = "0.5"
