[package]
name = "wipple_projects"
version = "0.0.0"
edition = "2018"

[dependencies]
git2 = "0.13.17"
reqwest = { version = "0.11.3", default-features = false, features = ["blocking", "native-tls", "native-tls-vendored"] }
rust-embed = "5.9.0"
serde = "1.0.125"
tempfile = "3.2.0"
wipple = { path = "../../language" }
wipple_stdlib = { path = "../../library" }
wipple_parser = { path = "../../parser" }
wipple_plugins = { path = "../../tooling/plugins" }
zip = "0.5.12"
