[package]
name = "wipple_compiler"
version = "0.0.0"
edition = "2018"

[dependencies]
bincode = "1"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
wipple_parser = { path = "../parser" }
