[package]
name = "wipple-fuzz"
version = "0.0.0"
edition = "2021"

[dependencies]
wipple-default-loader = { path = "../../loaders/default" }
wipple-frontend = { path = "../../frontend" }
wipple-interpreter-backend = { path = "../../backends/interpreter" }
