[package]
name = "wipple-fuzz"
version = "0.0.0"
edition = "2021"

[dependencies]
arbitrary = "1"
backtrace = "0.3"
clap = { version = "3", features = ["derive"] }
clearscreen = "2"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
wipple-default-loader = { path = "../../loaders/default" }
wipple-frontend = { path = "../../frontend", features = ["arbitrary"] }
