[package]
name = "wipple-cli"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "wipple"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
codemap = "=0.1.2"
codemap-diagnostic = "0.1"
indicatif = "0.16"
prettyplease = "0.1"
serde_json = "1"
syn = "1"
tokio = { version = "1", features = ["full"] }
wipple-default-loader = { path = "../loaders/default" }
wipple-frontend = { path = "../frontend", features = ["clap"] }
wipple-interpreter-backend = { path = "../backends/interpreter" }
wipple-rust-backend = { path = "../backends/rust" }
