[package]
name = "wipple_cli"
version = "0.0.0"
edition = "2018"

[dependencies]
codemap = "0.1"
codemap-diagnostic = "0.1"
structopt = "0.3"
wipple_bytecode = { path = "../bytecode" }
wipple_compiler = { path = "../frontend" }
wipple_interpreter = { path = "../backends/interpreter" }
