[package]
name = "wipple_cli"
version = "0.0.0"
edition = "2018"

[dependencies]
colored = "2.0.0"
libc = "0.2.93"
reqwest = { version = "0.11.3", default-features = false, features = ["blocking", "native-tls", "native-tls-vendored"] }
structopt = "0.3.21"
wipple = { path = "../core" }
wipple_bundled_interpreter = { path = "../bundled-interpreter" }
wipple_parser = { path = "../parser" }
wipple_projects = { path = "../projects" }
wipple_stdlib = { path = "../standard-library" }
zip = "0.5.12"
zip-extensions = "0.6.0"
