[package]
name = "wipple-cli"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "wipple"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
codemap = "=0.1.2"
codemap-diagnostic = "0.1"
indicatif = "0.16"
serde_json = "1"
wipple-bundled-backend = { path = "../backends/bundled/builder" }
wipple-compiler = { path = "../compiler", features = ["clap"] }
wipple-default-loader = { path = "../loaders/default" }
wipple-interpreter-backend = { path = "../backends/interpreter" }
