[package]
name = "wipple-cli"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "wipple"
path = "src/main.rs"


[lints]
workspace = true

[dependencies]
wipple-driver = { path = "../compiler/driver" }
