[package]
name = "wipple"
version = "0.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "1"
async-std = { version = "1", features = ["attributes"] }
clap = { version = "4", features = ["derive"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wipple-driver = { path = "../compiler/driver" }
wipple-interpreter = { path = "../interpreter" }
wipple-render = { path = "../render"}
