[package]
name = "wipple_bytecode"
version = "0.0.0"
edition = "2018"

[dependencies]
bincode = "1"
chic = "1"
ess = "0.4"
hex = "0.4"
line-col = "0.2"
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
