[book]
authors = ["Wilson Gramer"]
language = "en"
multilingual = false
src = "src"
title = "Wipple Compiler Documentation"

[build]
build-dir = "../_site/compiler-docs"

[output.html]
site-url = "/compiler-docs/"
git-repository-url = "https://github.com/wipplelang/wipple"
curly-quotes = true
additional-js = ["scripts/language-wipple.js"]
