[package]
name = "wipple-util"
version = "0.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
web-sys = { version = "0.3", features = ["console"] }
