[package]
name = "wipple-util"
version = "0.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
zstd = "0.13"
