[package]
name = "wipple_bundled_backend_runner"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
wipple_frontend = { path = "../../../frontend" }
wipple_interpreter_backend = { path = "../../interpreter" }
