[package]
name = "wipple-interpreter-backend"
version = "0.0.0"
edition = "2021"

[dependencies]
itertools = "0.10"
lazy_static = "1"
num-traits = "0.2"
rust_decimal = { version = "1", features = ["maths"] }
wipple-compiler = { path = "../../compiler" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libffi = { version = "3", features = ["system"] }
libloading = "0.7"
