[package]
name = "wipple-interpreter-backend"
version = "0.0.0"
edition = "2021"

[dependencies]
itertools = "0.10"
num-traits = "0.2"
rust_decimal = { version = "1", features = ["maths"] }
wipple-frontend = { path = "../../frontend" }
