[package]
name = "wipple-interpreter-backend"
version = "0.0.0"
edition = "2021"

[dependencies]
im = "15"
itertools = "0.10"
lazy_static = "1"
paste = "1"
wipple-compiler = { path = "../../compiler" }
