[package]
name = "wipple_stdlib"
version = "0.0.0"
edition = "2018"

[lib]
path = "builtins/lib.rs"

[dependencies]
rust_decimal = { version = "1", features = ["maths"] }
rust-embed = "5"
wipple = { path = "../language" }
wipple_parser = { path = "../parser" }
