[package]
name = "wipple-typecheck"
version = "0.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
derivative = "2"
itertools = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wipple-util = { path = "../../util" }
