[package]
name = "wipple-rust-backend"
version = "0.0.0"
edition = "2021"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
thiserror = "1"
wipple-frontend = { path = "../../frontend" }
