[book]
language = "en"
multilingual = false
src = "src"
title = "Wipple Documentation"

[preprocessor.template]

[output.html]
site-url = "/docs/"
no-section-label = true
additional-js = ["js/custom.js"]

[output.html.code.hidelines]
wipple = "#"
