[package]
name = "wipple_frontend"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
enum_dispatch = "0.3"
interned-string = { path = "../helpers/interned-string" }
kind = { path = "../helpers/kind" }
lazy_static = "1"
paste = "1"
polytype = { git = "https://github.com/WilsonGramer/polytype-rs", branch = "serde", features = ["serde"] }
rust_decimal = "1"
serde = { version = "1", features = ["derive", "rc"] }
url = "2"
wipple_diagnostics = { path = "../diagnostics" }
wipple_parser = { path = "../parser" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11", features = ["blocking"] }
