[package]
name = "wipple_frontend"
version = "0.0.0"
edition = "2021"

[dependencies]
enum_dispatch = "0.3"
kind = { path = "../helpers/kind" }
lazy_static = "1"
paste = "1"
serde = { version = "1", features = ["derive", "rc"] }
url = "2"
wipple_diagnostics = { path = "../diagnostics" }
wipple_parser = { path = "../parser" }
