[package]
name = "wipple_frontend"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
enum_dispatch = "0.3"
kind = { path = "../helpers/kind" }
lazy_static = "1"
openssl = { version = "0.10", features = ["vendored"] }
paste = "1"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1", features = ["derive", "rc"] }
url = "2"
wipple_diagnostics = { path = "../diagnostics" }
wipple_parser = { path = "../parser" }
