[package]
name = "wipple-lower"
version = "0.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
derivative = "2"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
strum = { version = "0.25", features = ["derive"] }
wipple-util = { path = "../../util" }
