[package]
name = "wipple-lower"
version = "0.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
derivative = "2"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
strum = { version = "0.25", features = ["derive"] }
ts-rs = { git = "https://github.com/WilsonGramer/ts-rs", branch = "concrete", features = ["no-serde-warnings"] }
wipple-util = { path = "../../util" }
