[package]
name = "wipple-render"
version = "0.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
annotate-snippets = "0.11"
line-index = "0.1"
serde = { version = "1", features = ["derive"] }
wipple-driver = { path = "../compiler/driver" }
