[package]
name = "wipple-syntax"
version = "0.0.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
derivative = "2"
rustc_lexer = "0.1"
serde = { version = "1", features = ["derive"] }
wipple-util = { path = "../../util" }
