[package]
name = "wipple-cli"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "wipple"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
codespan-reporting = "0.11"
indicatif = "0.16"
mktemp = "0.4"
prettyplease = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
subprocess = "0.2"
syn = "1"
tokio = { version = "1", features = ["full"] }
which = "4"
wipple-default-loader = { path = "../../loaders/default" }
wipple-frontend = { path = "../../frontend", features = ["clap", "serde_json"] }
wipple-interpreter-backend = { path = "../../backends/interpreter" }
