[package]
name = "wipple-lsp-backend"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
line-col = "0.2"
lsp-server = "0.6"
lsp-types = "0.93"
serde = "1"
serde_json = "1"
wipple-compiler = { path = "../../compiler" }
