[package]
name = "wipple-playground-runner"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]
debug_playground = ["rust-embed"]

[dependencies]
anyhow = "1"
console_error_panic_hook = { version = "0.1.6", optional = true }
force-send-sync = "1"
futures = "0.3"
itertools = "0.10"
js-sys = "0.3"
lazy_static = "1"
nonoverlapping_interval_tree = "0.1"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.5"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["console", "Response", "Request", "WorkerGlobalScope"] }
wipple-default-loader = { path = "../../../loaders/default" }
wipple-frontend = { path = "../../../frontend" }
wipple-interpreter-backend = { path = "../../../backends/interpreter" }
wipple-syntax = { path = "../../../syntax" }
rust-embed = { version = "6", features = ["debug-embed", "interpolate-folder-path"], optional = true }
send_wrapper = "0.6"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false  # FIXME: wasm-opt currently crashes
