[package]
name = "wipple_playground_runner"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
console_error_panic_hook = { version = "0.1.6", optional = true }
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2.73", features = ["serde-serialize"] }
wipple_diagnostics = { path = "../../../src/diagnostics" }
wipple_formatter = { path = "../../../src/formatter" }
wipple_frontend = { path = "../../../src/frontend" }
wipple_parser = { path = "../../../src/parser" }
