[package]
name = "wipple-playground-runner"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]
debug_playground = ["rust-embed"]

[dependencies]
anyhow = "1"
codemap = "=0.1.2"
codemap-diagnostic = "0.1"
console_error_panic_hook = { version = "0.1.6", optional = true }
itertools = "0.10"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
web-sys = { version = "0.3", features = ["console"] }
wipple-compiler = { path = "../../../compiler" }
wipple-default-loader = { path = "../../../loaders/default" }
wipple-interpreter-backend = { path = "../../../backends/interpreter" }
rust-embed = { version = "6", features = ["debug-embed", "interpolate-folder-path"], optional = true }
