[package]
name = "wipple-playground-runner"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
console_error_panic_hook = { version = "0.1.6", optional = true }
lazy_static = "1"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wipple-compiler = { path = "../../../compiler" }
wipple-interpreter-backend = { path = "../../../backends/interpreter" }
wipple-prelude = { path = "../../../prelude" }
