[package]
name = "wipple_stdlib"
version = "0.0.0"
edition = "2018"

[dependencies]
rust-embed = "5.9.0"
wipple = { path = "../core" }
wipple_parser = { path = "../parser" }
wipple_plugins = { path = "../plugins" }
wipple_projects = { path = "../projects" }
