on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/**
      - src/**

name: Build

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: short_sha
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - uses: ncipollo/release-action@v1
        with:
          name: Wipple Development Snapshot (${{ steps.short_sha.outputs.short_sha }})
          tag: 0.0.0-dev-${{ github.sha }}
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            compiler: cargo
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   compiler: cross
          - os: macos-latest
            target: x86_64-apple-darwin
            compiler: cargo

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.target }}

      - run: .github/scripts/build.sh ${{ matrix.target }} ${{ matrix.compiler }}

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/*
          file_glob: true
          tag: 0.0.0-dev-${{ github.sha }}
