on:
  workflow_dispatch:
  push:
    paths:
      - .github/**
      - bundled-interpreter/**
      - cli/**
      - core/**
      - loading/**
      - parser/**
      - plugins/**
      - projects/**
      - standard-library/**

name: Build

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ncipollo/release-action@v1
        with:
          name: Wipple Development Snapshot
          tag: 0.0.0-dev-${{ github.sha }}
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        target:
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
        include:
          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo

      - run: ./scripts/build.sh ${{ matrix.target }}

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/*
          file_glob: true
          tag: 0.0.0-dev-${{ github.sha }}
