on:
    - workflow_call

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: arduino/setup-task@v1

            - uses: actions/setup-node@v4
              with:
                  node-version: 21

            - uses: Swatinem/rust-cache@v2.2.0
              with:
                  workspaces: |
                      compiler
                  cache-on-failure: true

            - run: |
                  rustup toolchain install stable --profile minimal
                  rustup target add wasm32-unknown-unknown
                  cargo install wasm-pack --no-default-features
                  cargo install wasm-bindgen-cli

            - run: |
                  cat <<EOF > web/playground/.env
                  VITE_FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}"
                  VITE_FIREBASE_AUTH_DOMAIN="${{ secrets.FIREBASE_AUTH_DOMAIN }}"
                  VITE_FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}"
                  VITE_FIREBASE_STORAGE_BUCKET="${{ secrets.FIREBASE_STORAGE_BUCKET }}"
                  VITE_FIREBASE_MESSAGING_SENDER_ID="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
                  VITE_FIREBASE_APP_ID="${{ secrets.FIREBASE_APP_ID }}"
                  VITE_FIREBASE_MEASUREMENT_ID="${{ secrets.FIREBASE_MEASUREMENT_ID }}"
                  EOF

            - run: task install-dependencies

            - run: task cli:build

            - run: task test

            - run: task doctest

            - uses: mikepenz/action-junit-report@v4
              if: success() || failure() # always run even if the previous step fails
              with:
                  check_name: "Doctests"
                  include_passed: true
                  report_paths: ".wipple/doctest/*.xml"

            - run: task web:build

            - uses: actions/upload-artifact@master
              with:
                  name: web-${{ github.sha }}
                  path: web/dist/
