on:
    workflow_dispatch:
    push:
        paths:
            - .github/**
            - backends/**
            - frontend/**
            - loaders/**
            - std/**
            - syntax/**
            - tests/**
            - tools/**
            - util/**
            - website/**
            - Cargo.toml
            - Cargo.lock
            - Cross.toml
        branches:
            - main

name: Trigger Deploy Website

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.REPOSITORY_DISPATCH_PAT }}
                  repository: wipplelang/wipplelang.github.io
                  event-type: deploy
