on:
    - workflow_dispatch
    - push

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: arduino/setup-task@v1

            - uses: Swatinem/rust-cache@v2.2.0
              with:
                  workspaces: |
                      compiler
                  cache-on-failure: true

            - run: |
                  rustup toolchain install stable --profile minimal
                  rustup target add wasm32-unknown-unknown
                  cargo install wasm-pack --no-default-features
                  cargo install wasm-bindgen-cli

            - run: task install-dependencies

            - run: task cli:build

            - run: task test
              env:
                  WIPPLE_TEST_PREFIX: ${{ github.workspace }}

    # TODO: Deploy website
