on:
    - workflow_dispatch
    - push

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: rustup toolchain install stable --profile minimal

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.2.0

            - run: .github/scripts/test.sh

            - uses: mikepenz/action-junit-report@v3
              if: always()
              with:
                  check_name: Wipple Test Report
                  require_tests: true
                  fail_on_failure: true

    website:
        name: Website
        runs-on: ubuntu-latest
        needs:
            - tests
        steps:
            - uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.REPOSITORY_DISPATCH_PAT }}
                  repository: wipplelang/wipplelang.github.io
                  event-type: deploy
