on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Build Docs
        runs-on: ubuntu-latest
        steps:
            - uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.REPOSITORY_DISPATCH_PAT }}
                  repository: wipplelang/docs-website
                  event-type: deploy
