on:
  release:
    types:
      - published

name: Upload Release Binaries

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            compiler: cargo

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            compiler: cross

          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            compiler: cross

          - os: macos-latest
            target: x86_64-apple-darwin
            compiler: cargo

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - id: latest-release
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - run: .github/scripts/build.sh ${{ matrix.target }} ${{ matrix.compiler }}

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/*
          file_glob: true
          tag: ${{ steps.latest-release.outputs.tag }}
