on:
  workflow_dispatch:
  push:
    paths:
      - .github/**
      - backends/**
      - frontend/**
      - loaders/**
      - pkg/**
      - tools/**

name: Tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: .github/scripts/test.sh

      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: Wipple Test Report
          require_tests: true
          fail_on_failure: true

      - run: .github/scripts/fuzz.sh
