on:
    workflow_dispatch:
    push:
        paths:
            - .github/**
            - backends/**
            - frontend/**
            - loaders/**
            - std/**
            - syntax/**
            - tests/**
            - tools/**
            - util/**
            - Cargo.toml
            - Cargo.lock
            - Cross.toml

name: tests

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - run: rustup toolchain install stable --profile minimal

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.2.0

            - run: .github/scripts/test.sh

            - uses: mikepenz/action-junit-report@v3
              if: always()
              with:
                  check_name: Wipple Test Report
                  require_tests: true
                  fail_on_failure: true
